name             "tomcat-solr"
maintainer       "Adam Cooper"
maintainer_email "adam@networkpie.co.uk"
license          "Apache 2.0"
description      "Installs/Configures solr"
version          "0.1.2"